name: checkout-and-run
on:
  pull_request:
    branches: [ master ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - run: yarn install
      - run: cd ./dev/cm5 && yarn install
